### ISSUE TITLE
demo的使用反馈

### ISSUE THREAD

**Issue by BurgessYT** [byTangs/RuntimeEditorDocumentation#1]
![image](https://user-images.githubusercontent.com/25280381/186057783-a3841628-d352-4e9b-a6a3-5a2a4e3bf1c0.png)
无法通过鼠标点击选中视口模型

![image](https://user-images.githubusercontent.com/25280381/186058003-c1cec278-c2d8-4dda-83df-80edb59bdc64.png)
点击play后并没有在编辑器中放置的模型

**Comment by byTangs** [comment]
目前还没有做坐标轴的功能和保存功能，当前版本是不支持点击选择物体的功能和实时修改保存的功能，这个会在后续的版本中加入；  现在的版本只是一个大概的版本，缺少很多功能，你可以再商城页面看到即将到来的功能；因为现在是一个在开发，所以开发进度不是很快；   实时关注插件的更新，又新功能加入，我就会更新商城的插件版本

**Comment by BurgessYT** [comment]
好的，感谢回复，等着被催更吧 😃
